![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

In [2]:
my_array=np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(sorted(my_array[np.where(my_array%2==1)],reverse=True))

[9, 7, 5, 3, 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [4]:
sorted(my_array,reverse=True)[1:3]

[8, 7]

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [5]:
sorted(my_array,reverse=True)[-3:]

[2, 1, 0]

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [6]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [7]:
np.arange(1,21).reshape(4,5).reshape(20)[::-1].reshape(4,5)

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [8]:
np.arange(1,21).reshape(4,5)[0:2,0:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [9]:
np.arange(1,21).reshape(4,5)[[0,2]][:,[0,2,4]]

array([[ 1,  3,  5],
       [11, 13, 15]])

In [10]:
np.arange(1,21).reshape(4,5)[np.ix_([0,2],[0,2,4],)]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [11]:
arr4=np.arange(1,21).reshape(4,5)
print(arr4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [12]:
np.flip(arr4,axis=1)[0:3]


array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

In [13]:
arr4[:,::-1][0:3]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [14]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [15]:
print(x=='Loro')

[ True False False  True False]


In [16]:
print(x[np.where(x=='Loro')])

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [17]:
np.arange(20).reshape(5,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [18]:
print(np.arange(1,21).reshape(4,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [19]:
print(np.arange(1,21).reshape(4,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [20]:
arr11=np.zeros(10)

In [21]:
arr11.itemsize

8

In [22]:
arr11[3]=1
print(arr11)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [23]:
arr12=np.arange(10,50)
print(arr12)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [24]:
print(arr12[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [25]:
print(np.array(list(reversed(arr12))))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [26]:
print(sorted(arr12,reverse=True))

[49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [27]:
arr13=np.array( [1,2,0,0,4,0])

In [28]:
list(np.where(arr13!=0)[0])

[0, 1, 4]

In [29]:
list(np.nonzero(arr13)[0])

[0, 1, 4]

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [30]:
arr14=np.random.rand(10,10)


In [31]:
np.max(arr14)


0.9946554072676783

In [32]:
np.min(arr14)

0.011923655780396003

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [33]:
arr15=np.random.rand(30)

In [34]:
arr15.mean()

0.5564410037552957

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [35]:
n=5
arr16=np.zeros((n,n))

In [36]:
arr16=np.zeros((n,n))
arr16[0,:]=1
arr16[-1,:]=1
arr16[:,0]=1
arr16[:,-1]=1

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [37]:
arr17=np.zeros((8,8),dtype=int)

for i in range(8):
    for j in range(8):
        arr17[i][j]=(i+j)%2!=0

In [38]:
print(arr17)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [39]:
arr17 = ((np.arange(8) + np.arange(8)[:, np.newaxis]) % 2 != 0).astype(int)

In [40]:
print(arr17)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [41]:
arr_tile=np.array([[0, 1],[1,0]])
arr18=np.tile(arr_tile,(4,4))
print(arr18)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [42]:
arr19=np.random.randint(25,size=(5,5))
arr19_norm=(arr19-np.mean(arr19))/np.std(arr19)
print(arr19,'\n\n',arr19_norm)

[[ 6  4 11  0  8]
 [12 13  5 10 22]
 [18  4  0 23  9]
 [22  2  7  0 10]
 [14 22 15 20 16]] 

 [[-0.67559986 -0.95023394  0.01098536 -1.49950212 -0.40096577]
 [ 0.14830241  0.28561945 -0.8129169  -0.12633168  1.52147285]
 [ 0.97220467 -0.95023394 -1.49950212  1.65878989 -0.26364872]
 [ 1.52147285 -1.22486803 -0.53828281 -1.49950212 -0.12633168]
 [ 0.4229365   1.52147285  0.56025354  1.24683876  0.69757058]]


In [43]:
sum(arr19_norm.flatten())

-1.1102230246251565e-16

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [44]:
arr20=np.arange(0,11)
print(arr20)


[ 0  1  2  3  4  5  6  7  8  9 10]


In [45]:
arr20[3:9]=-1
print(arr20)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [46]:
arr20[3:9]=not arr20[3:9].all
print(arr20)

[ 0  1  2  0  0  0  0  0  0  9 10]


## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [47]:
#### Bonus track. Mini hundir la flota

In [48]:
from IPython.display import Markdown
import numpy as np


def imprimir_tablero_markdown(tablero):
    n, m = tablero.shape
    markdown = "| " + " | ".join([""] + [f"<center>{str(i-1).center(2)}</center>" for i in range(1, m+1)]) + " |\n"
    markdown += "|-" + "|".join(["-" * 5] + ["-" * 5 for _ in range(m)]) + "|\n"
    
    for i in range(n):
        fila = "| " + " | ".join([f"<center>{str(i).center(2)}</center>"] + [f"<center>{str(cell).center(2)}</center>" for cell in tablero[i]]) + " |\n"
        markdown += fila

    return Markdown(markdown)



In [49]:
#1. Crea un tablero de 10x10 relleno del carácter espacio ( ).

tablero = np.full((10,10)," ",dtype=str)
imprimir_tablero_markdown(tablero)


|  | <center>0 </center> | <center>1 </center> | <center>2 </center> | <center>3 </center> | <center>4 </center> | <center>5 </center> | <center>6 </center> | <center>7 </center> | <center>8 </center> | <center>9 </center> |
|------|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| <center>0 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>1 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>2 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>3 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>4 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>5 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>6 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>7 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>8 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>9 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |


In [50]:
#2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
barco1=np.array([(0,1), (1,1)] )
barco2=np.array([(1,3), (1,4), (1,5), (1,6)])

In [51]:
def coloca_barco(tablero,barco):
    for i,j in barco:
        tablero[i,j]='O'

In [52]:
for barco in [barco1,barco2]:
    coloca_barco(tablero,barco)
imprimir_tablero_markdown(tablero)

|  | <center>0 </center> | <center>1 </center> | <center>2 </center> | <center>3 </center> | <center>4 </center> | <center>5 </center> | <center>6 </center> | <center>7 </center> | <center>8 </center> | <center>9 </center> |
|------|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| <center>0 </center> | <center>  </center> | <center>O </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>1 </center> | <center>  </center> | <center>O </center> | <center>  </center> | <center>O </center> | <center>O </center> | <center>O </center> | <center>O </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>2 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>3 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>4 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>5 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>6 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>7 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>8 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>9 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |


In [53]:
#3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
def disparar(fila,columna):
    disparo=np.array([(fila,columna)])
    for i,j in disparo:
        if tablero[i,j] == "O":
            tablero[i,j] = "X"
    return(imprimir_tablero_markdown(tablero)) 
    


In [54]:
disparar(0,1)

|  | <center>0 </center> | <center>1 </center> | <center>2 </center> | <center>3 </center> | <center>4 </center> | <center>5 </center> | <center>6 </center> | <center>7 </center> | <center>8 </center> | <center>9 </center> |
|------|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| <center>0 </center> | <center>  </center> | <center>X </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>1 </center> | <center>  </center> | <center>O </center> | <center>  </center> | <center>O </center> | <center>O </center> | <center>O </center> | <center>O </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>2 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>3 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>4 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>5 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>6 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>7 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>8 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>9 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |


In [55]:
#4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
def disparar(fila,columna):
    disparo=np.array([(fila,columna)])
    for i,j in disparo:
        if tablero[i,j] == "O":
            tablero[i,j] = "X"
        elif tablero[i,j] == " ":
            tablero[i,j] = "-"
    return(imprimir_tablero_markdown(tablero)) 

In [56]:
disparar(8,3)

|  | <center>0 </center> | <center>1 </center> | <center>2 </center> | <center>3 </center> | <center>4 </center> | <center>5 </center> | <center>6 </center> | <center>7 </center> | <center>8 </center> | <center>9 </center> |
|------|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| <center>0 </center> | <center>  </center> | <center>X </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>1 </center> | <center>  </center> | <center>O </center> | <center>  </center> | <center>O </center> | <center>O </center> | <center>O </center> | <center>O </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>2 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>3 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>4 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>5 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>6 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>7 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>8 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>- </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>9 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |


In [57]:
#5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**



In [58]:
import numpy as np

def posicionar_barco_aleatorio(tablero, lon_barco):
    n, m = tablero.shape
    orientaciones = ["N", "S", "E", "O"]

    while True:
        # Generar posición inicial aleatoria
        fila = np.random.randint(0, n)
        columna = np.random.randint(0, m)
        orientacion = np.random.choice(orientaciones)

        # Verificar si el barco cabe en la posición y orientación elegidas
        if orientacion == "N":
            if fila - lon_barco >= 0:
                casillas_libres = tablero[fila - lon_barco + 1:fila + 1, columna]
            else:
                continue
        elif orientacion == "S":
            if fila + lon_barco <= n - 1:
                casillas_libres = tablero[fila:fila + lon_barco, columna]
            else:
                continue
        elif orientacion == "E":
            if columna + lon_barco <= m - 1:
                casillas_libres = tablero[fila, columna:columna + lon_barco]
            else:
                continue
        elif orientacion == "O":
            if columna - lon_barco >= 0:
                casillas_libres = tablero[fila, columna - lon_barco + 1:columna + 1]
            else:
                continue

        # Verificar si las casillas están libres (cadenas vacías)
        if np.all(casillas_libres == ''):
            # Crear una lista de las posiciones ocupadas por el barco
            posiciones_barco = []
            if orientacion == "N":
                for i in range(fila - lon_barco + 1, fila + 1):
                    posiciones_barco.append((i, columna))
            elif orientacion == "S":
                for i in range(fila, fila + lon_barco):
                    posiciones_barco.append((i, columna))
            elif orientacion == "E":
                for j in range(columna, columna + lon_barco):
                    posiciones_barco.append((fila, j))
            elif orientacion == "O":
                for j in range(columna - lon_barco + 1, columna + 1):
                    posiciones_barco.append((fila, j))

            # Colocar el barco en el tablero como texto
            coloca_barco(tablero,posiciones_barco)

            return posiciones_barco


In [73]:
ndim_tablero = 10
tablero = np.full((ndim_tablero, ndim_tablero), "", dtype=str)
longitud_barco = 4
posiciones_barco = posicionar_barco_aleatorio(tablero, longitud_barco)
imprimir_tablero_markdown(tablero)




|  | <center>0 </center> | <center>1 </center> | <center>2 </center> | <center>3 </center> | <center>4 </center> | <center>5 </center> | <center>6 </center> | <center>7 </center> | <center>8 </center> | <center>9 </center> |
|------|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| <center>0 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>1 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>2 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>3 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>4 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>5 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>O </center> | <center>  </center> |
| <center>6 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>O </center> | <center>  </center> |
| <center>7 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>O </center> | <center>  </center> |
| <center>8 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>O </center> | <center>  </center> |
| <center>9 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |


In [60]:
posiciones_barco = posicionar_barco_aleatorio(tablero, longitud_barco)
imprimir_tablero_markdown(tablero)

|  | <center>0 </center> | <center>1 </center> | <center>2 </center> | <center>3 </center> | <center>4 </center> | <center>5 </center> | <center>6 </center> | <center>7 </center> | <center>8 </center> | <center>9 </center> |
|------|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| <center>0 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>O </center> | <center>O </center> | <center>O </center> | <center>O </center> | <center>  </center> |
| <center>1 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>2 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>O </center> | <center>O </center> | <center>O </center> | <center>O </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>3 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>4 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>5 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>6 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>7 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>8 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
| <center>9 </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> | <center>  </center> |
